/**
 * below constants are from table named permission in database
WATCHINGLIMITEDPERDAY
WATCHINGNOLIMITED
DOWNLOADINGNOLIMITED
FASTFORWARD
SUBMITEVALUATION
SUBMITISSUE
 */

const WATCHINGLIMITEDPERDAY = "WATCHINGLIMITEDPERDAY";
const WATCHINGNOLIMITED = "WATCHINGNOLIMITED";
const DOWNLOADINGNOLIMITED = "DOWNLOADINGNOLIMITED";
const FASTFORWARD = "FASTFORWARD";
const SUBMITEVALUATION = "SUBMITEVALUATION";
const SUBMITISSUE = "SUBMITISSUE";

export default {
  WATCHINGLIMITEDPERDAY,
  WATCHINGNOLIMITED,
  DOWNLOADINGNOLIMITED,
  FASTFORWARD,
  SUBMITEVALUATION,
  SUBMITISSUE
};
