const NOPERMISSION="会员等级不足"
const NOPERMISSIONTOOPERATION="您当前会员等级不支持此操作，请升级，详情请见个人信息会员详情"
const BEYONDWATCHINGLIMITEDCOUNTPERDAY="您当天观看视频数量已超出您当前会员等级限制，请明天观看或升级您的会员等级，详情请见个人信息会员详情"
const VIDEOWATCHINGLIMITATIONIMAGEURL="http://video.chengxuxiaoba.com/image/default/58E527F95AFE49B3976ECB030AD5FBED-6-2.png"
const NOLOGINIMAGEURL="http://video.chengxuxiaoba.com/image/default/AEB830614AF441B99370A1E388A2BE39-6-2.png"
export default {
    NOPERMISSION,
    NOPERMISSIONTOOPERATION,
    BEYONDWATCHINGLIMITEDCOUNTPERDAY,
    VIDEOWATCHINGLIMITATIONIMAGEURL,
    NOLOGINIMAGEURL
  };